# EuroAutoDataHub/docker-compose.yml
version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: euroautodatahub_postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняет данные БД между перезапусками контейнера
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-max}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
      - POSTGRES_DB=${POSTGRES_DB:-euroautodatahub_db}
    restart: unless-stopped

volumes:
  postgres_data: