"""create_car_tables_with_sqlmodel

Revision ID: 4a3f378a47b2
Revises: 
Create Date: 2025-05-18 13:44:23.332258

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3f378a47b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_make',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_make_name'), 'car_make', ['name'], unique=False)
    op.create_index(op.f('ix_car_make_slug'), 'car_make', ['slug'], unique=True)
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['car_make.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_model_make_id'), 'car_model', ['make_id'], unique=False)
    op.create_index(op.f('ix_car_model_name'), 'car_model', ['name'], unique=False)
    op.create_index(op.f('ix_car_model_slug'), 'car_model', ['slug'], unique=True)
    op.create_table('auto_ad',
    sa.Column('id_ad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('make_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url_ad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currencyCode', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gearbox', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine_capacity', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine_power', sa.Integer(), nullable=True),
    sa.Column('sellerLink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('car_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_model.id'], ),
    sa.PrimaryKeyConstraint('id_ad')
    )
    op.create_index(op.f('ix_auto_ad_car_model_id'), 'auto_ad', ['car_model_id'], unique=False)
    op.create_index(op.f('ix_auto_ad_city'), 'auto_ad', ['city'], unique=False)
    op.create_index(op.f('ix_auto_ad_id_ad'), 'auto_ad', ['id_ad'], unique=False)
    op.create_index(op.f('ix_auto_ad_mileage'), 'auto_ad', ['mileage'], unique=False)
    op.create_index(op.f('ix_auto_ad_price'), 'auto_ad', ['price'], unique=False)
    op.create_index(op.f('ix_auto_ad_url_ad'), 'auto_ad', ['url_ad'], unique=True)
    op.create_index(op.f('ix_auto_ad_year'), 'auto_ad', ['year'], unique=False)
    op.create_table('auto_ad_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_ad_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currencyCode', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['auto_ad_id'], ['auto_ad.id_ad'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_ad_history_auto_ad_id'), 'auto_ad_history', ['auto_ad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_ad_history_auto_ad_id'), table_name='auto_ad_history')
    op.drop_table('auto_ad_history')
    op.drop_index(op.f('ix_auto_ad_year'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_url_ad'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_price'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_mileage'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_id_ad'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_city'), table_name='auto_ad')
    op.drop_index(op.f('ix_auto_ad_car_model_id'), table_name='auto_ad')
    op.drop_table('auto_ad')
    op.drop_index(op.f('ix_car_model_slug'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_name'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_make_id'), table_name='car_model')
    op.drop_table('car_model')
    op.drop_index(op.f('ix_car_make_slug'), table_name='car_make')
    op.drop_index(op.f('ix_car_make_name'), table_name='car_make')
    op.drop_table('car_make')
    # ### end Alembic commands ###
