"""add generation column to auto_ad table

Revision ID: 5a299a3c0a9c
Revises: 4a3f378a47b2
Create Date: 2025-05-25 13:45:48.535209

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a299a3c0a9c'
down_revision: Union[str, None] = '4a3f378a47b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_ad', sa.Column('generation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_auto_ad_generation'), 'auto_ad', ['generation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_ad_generation'), table_name='auto_ad')
    op.drop_column('auto_ad', 'generation')
    # ### end Alembic commands ###
