"""ML (этап 5): реестр моделей ml_model, интервалы и deal score в listing_price_estimate, прогноз срока
до снятия listing_dom_forecast, межстрановой арбитраж arbitrage_opportunity; v_listing с этими полями

Revision ID: 71711b2e6ec0
Revises: d2a6f4b8c9e1
Create Date: 2026-10-04 09:55:34.280778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import eadh_common.models  # noqa: F401  (пользовательские типы, например UTCDateTime)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71711b2e6ec0'
down_revision: Union[str, None] = 'd2a6f4b8c9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# v_listing ревизии d2a6f4b8c9e1; новая версия добавляет интервал цены, deal score и прогноз срока до снятия
V_LISTING_SELECT = """
    SELECT l.*,
           vm.slug AS make_slug, vm.name AS make_name,
           vmo.slug AS model_slug, vmo.name AS model_name,
           EXTRACT(DAY FROM (CASE WHEN l.status = 'delisted' THEN l.last_seen_at ELSE now() END)
                            - l.first_seen_at)::int AS days_on_market,
           (l.quality_flags IS NULL) AS quality_ok,
           e.expected_price_eur, e.deviation AS price_deviation, e.robust_z AS price_z,
           e.segment_level AS price_segment_level, e.segment_size AS price_segment_size,
           dup.canonical_id AS duplicate_of, dup.method AS duplicate_method{extra}
    FROM listing l
    LEFT JOIN vehicle_make vm ON vm.id = l.make_id
    LEFT JOIN vehicle_model vmo ON vmo.id = l.model_id
    LEFT JOIN listing_price_estimate e ON e.listing_id = l.id
    LEFT JOIN listing_duplicate dup ON dup.listing_id = l.id{join}
"""
V_LISTING_EXTRA = """,
           e.method AS price_method, e.model_version AS price_model_version,
           e.p10_eur AS expected_price_p10_eur, e.p90_eur AS expected_price_p90_eur, e.deal_score,
           f.expected_days AS dom_expected_days, f.remaining_days AS dom_remaining_days"""
V_LISTING_JOIN = "\n    LEFT JOIN listing_dom_forecast f ON f.listing_id = l.id"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('trained_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('activated_at', eadh_common.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('train_from', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_valid', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('features', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artifact', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'version', name='uq_ml_model_kind_version')
    )
    op.create_index('ix_ml_model_kind_status', 'ml_model', ['kind', 'status'], unique=False)
    op.create_table('arbitrage_opportunity',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('from_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('to_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_p50_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_p10_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('transport_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('import_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('costs', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('profit_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit_p10_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('comparables', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbitrage_opportunity_listing_id'), 'arbitrage_opportunity', ['listing_id'], unique=False)
    op.create_index(op.f('ix_arbitrage_opportunity_profit_eur'), 'arbitrage_opportunity', ['profit_eur'], unique=False)
    op.create_index('ix_arbitrage_route', 'arbitrage_opportunity', ['from_country', 'to_country'], unique=False)
    op.create_table('listing_dom_forecast',
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('probabilities', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_days', sa.Float(), nullable=True),
    sa.Column('remaining_days', sa.Float(), nullable=True),
    sa.Column('age_days', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    # у уже посчитанных оценок метод — сегмент (v1)
    op.add_column('listing_price_estimate', sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False,
                                                      server_default='segment'))
    op.alter_column('listing_price_estimate', 'method', server_default=None)
    op.add_column('listing_price_estimate', sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('listing_price_estimate', sa.Column('p10_eur', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('listing_price_estimate', sa.Column('p90_eur', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('listing_price_estimate', sa.Column('price_percentile', sa.Float(), nullable=True))
    op.add_column('listing_price_estimate', sa.Column('deal_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listing_price_estimate_deal_score'), 'listing_price_estimate', ['deal_score'], unique=False)
    # ### end Alembic commands ###
    op.execute("DROP VIEW IF EXISTS v_listing")
    op.execute("CREATE VIEW v_listing AS" + V_LISTING_SELECT.format(extra=V_LISTING_EXTRA, join=V_LISTING_JOIN))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS v_listing")
    op.execute("CREATE VIEW v_listing AS" + V_LISTING_SELECT.format(extra="", join=""))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_price_estimate_deal_score'), table_name='listing_price_estimate')
    op.drop_column('listing_price_estimate', 'deal_score')
    op.drop_column('listing_price_estimate', 'price_percentile')
    op.drop_column('listing_price_estimate', 'p90_eur')
    op.drop_column('listing_price_estimate', 'p10_eur')
    op.drop_column('listing_price_estimate', 'model_version')
    op.drop_column('listing_price_estimate', 'method')
    op.drop_table('listing_dom_forecast')
    op.drop_index('ix_arbitrage_route', table_name='arbitrage_opportunity')
    op.drop_index(op.f('ix_arbitrage_opportunity_profit_eur'), table_name='arbitrage_opportunity')
    op.drop_index(op.f('ix_arbitrage_opportunity_listing_id'), table_name='arbitrage_opportunity')
    op.drop_table('arbitrage_opportunity')
    op.drop_index('ix_ml_model_kind_status', table_name='ml_model')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
