"""Аномалии, оценки справедливой цены, подписки на дайджест, флаги качества объявлений

Revision ID: b5e8d1c3a7f2
Revises: 9c4d2a7f1b30
Create Date: 2026-09-30 16:02:16.646702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import eadh_common.models  # noqa: F401  (пользовательские типы, например UTCDateTime)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e8d1c3a7f2'
down_revision: Union[str, None] = '9c4d2a7f1b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# v_listing из миграции 9c4d2a7f1b30 (l.* раскрывается при создании представления, поэтому оно пересоздаётся)
V_LISTING_OLD = """
    CREATE VIEW v_listing AS
    SELECT l.*,
           vm.slug AS make_slug, vm.name AS make_name,
           vmo.slug AS model_slug, vmo.name AS model_name,
           EXTRACT(DAY FROM (CASE WHEN l.status = 'delisted' THEN l.last_seen_at ELSE now() END)
                            - l.first_seen_at)::int AS days_on_market
    FROM listing l
    LEFT JOIN vehicle_make vm ON vm.id = l.make_id
    LEFT JOIN vehicle_model vmo ON vmo.id = l.model_id
"""

V_LISTING = """
    CREATE VIEW v_listing AS
    SELECT l.*,
           vm.slug AS make_slug, vm.name AS make_name,
           vmo.slug AS model_slug, vmo.name AS model_name,
           EXTRACT(DAY FROM (CASE WHEN l.status = 'delisted' THEN l.last_seen_at ELSE now() END)
                            - l.first_seen_at)::int AS days_on_market,
           (l.quality_flags IS NULL) AS quality_ok,
           e.expected_price_eur, e.deviation AS price_deviation, e.robust_z AS price_z,
           e.segment_level AS price_segment_level, e.segment_size AS price_segment_size
    FROM listing l
    LEFT JOIN vehicle_make vm ON vm.id = l.make_id
    LEFT JOIN vehicle_model vmo ON vmo.id = l.model_id
    LEFT JOIN listing_price_estimate e ON e.listing_id = l.id
"""

V_ANOMALY = """
    CREATE VIEW v_anomaly AS
    SELECT a.*,
           vm.slug AS make_slug, vm.name AS make_name,
           vmo.slug AS model_slug, vmo.name AS model_name,
           l.url AS listing_url, l.title AS listing_title, l.status AS listing_status,
           l.price_eur AS listing_price_eur, l.year AS listing_year, l.mileage_km AS listing_mileage_km
    FROM anomaly a
    LEFT JOIN listing l ON l.id = a.listing_id
    LEFT JOIN vehicle_make vm ON vm.id = COALESCE(a.make_id, l.make_id)
    LEFT JOIN vehicle_model vmo ON vmo.id = COALESCE(a.model_id, l.model_id)
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_discount', sa.Float(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', eadh_common.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('segment_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('first_detected_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status_changed_at', eadh_common.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notified_at', eadh_common.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_anomaly_kind_date', 'anomaly', ['kind', 'detected_on'], unique=False)
    op.create_index(op.f('ix_anomaly_listing_id'), 'anomaly', ['listing_id'], unique=False)
    op.create_index('ix_anomaly_rule_status', 'anomaly', ['rule', 'status'], unique=False)
    op.create_index(op.f('ix_anomaly_run_id'), 'anomaly', ['run_id'], unique=False)
    op.create_table('listing_price_estimate',
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_price_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('robust_z', sa.Float(), nullable=False),
    sa.Column('segment_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('segment_size', sa.Integer(), nullable=False),
    sa.Column('segment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listing_price_estimate_deviation'), 'listing_price_estimate', ['deviation'], unique=False)
    op.add_column('listing', sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###

    # До этой ревизии Python None в JSON-колонках записывался как JSON null, а не SQL NULL
    for table, column in (("crawl_run", "stats"), ("crawl_run", "report")):
        op.execute(f"UPDATE {table} SET {column} = NULL WHERE jsonb_typeof({column}) = 'null'")

    op.execute("DROP VIEW IF EXISTS v_listing")
    op.execute(V_LISTING)
    op.execute(V_ANOMALY)
    # Флаги качества уже накопленных объявлений ingestor проставит при ближайшей проверке
    # (app.quality.refresh_quality_flags после прогона); до этого они считаются корректными.


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS v_anomaly")
    op.execute("DROP VIEW IF EXISTS v_listing")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'quality_flags')
    op.drop_index(op.f('ix_listing_price_estimate_deviation'), table_name='listing_price_estimate')
    op.drop_table('listing_price_estimate')
    op.drop_index(op.f('ix_anomaly_run_id'), table_name='anomaly')
    op.drop_index('ix_anomaly_rule_status', table_name='anomaly')
    op.drop_index(op.f('ix_anomaly_listing_id'), table_name='anomaly')
    op.drop_index('ix_anomaly_kind_date', table_name='anomaly')
    op.drop_table('anomaly')
    op.drop_table('alert_subscription')
    # ### end Alembic commands ###
    op.execute(V_LISTING_OLD)
