"""Дубли объявлений между площадками (listing_duplicate), v_listing с duplicate_of

Revision ID: d2a6f4b8c9e1
Revises: b5e8d1c3a7f2
Create Date: 2026-09-30 17:15:15.419179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import eadh_common.models  # noqa: F401  (пользовательские типы, например UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'd2a6f4b8c9e1'
down_revision: Union[str, None] = 'b5e8d1c3a7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# v_listing из ревизии b5e8d1c3a7f2 и новая версия с каноничным объявлением дубля
V_LISTING_SELECT = """
    SELECT l.*,
           vm.slug AS make_slug, vm.name AS make_name,
           vmo.slug AS model_slug, vmo.name AS model_name,
           EXTRACT(DAY FROM (CASE WHEN l.status = 'delisted' THEN l.last_seen_at ELSE now() END)
                            - l.first_seen_at)::int AS days_on_market,
           (l.quality_flags IS NULL) AS quality_ok,
           e.expected_price_eur, e.deviation AS price_deviation, e.robust_z AS price_z,
           e.segment_level AS price_segment_level, e.segment_size AS price_segment_size{extra}
    FROM listing l
    LEFT JOIN vehicle_make vm ON vm.id = l.make_id
    LEFT JOIN vehicle_model vmo ON vmo.id = l.model_id
    LEFT JOIN listing_price_estimate e ON e.listing_id = l.id{join}
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_duplicate',
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detected_at', eadh_common.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['listing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listing_duplicate_canonical_id'), 'listing_duplicate', ['canonical_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("DROP VIEW IF EXISTS v_listing")
    op.execute("CREATE VIEW v_listing AS" + V_LISTING_SELECT.format(
        extra=",\n           dup.canonical_id AS duplicate_of, dup.method AS duplicate_method",
        join="\n    LEFT JOIN listing_duplicate dup ON dup.listing_id = l.id"))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS v_listing")
    op.execute("CREATE VIEW v_listing AS" + V_LISTING_SELECT.format(extra="", join=""))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_duplicate_canonical_id'), table_name='listing_duplicate')
    op.drop_table('listing_duplicate')
    # ### end Alembic commands ###
